### ISSUE TITLE
Convert glyph outlined path to single line bezier path 

### ISSUE THREAD

**Issue by alyfreym** [SusanDoggie/Doggie#12]
Hi its possible using this lib convert outlined glyph path to single line path? I pin example image what I mean. Any suggestion please, or article. 
![Group 3](https://user-images.githubusercontent.com/29518174/202889629-49d43885-a1cc-499f-978f-bf2b2340a1ac.png)

**Comment by SusanDoggie** [comment]
Hello,
ShapeRegion can convert paths to contour paths by providing winding rules.

```swift
let original = try Shape(code: "M100 0c0-100-236.60 36.60-150 86.60S36.60-136.60-50-86.60 100 100 100 0z")
let contour = ShapeRegion(original, winding: .nonZero)
```

**Comment by alyfreym** [comment]
> Hello, ShapeRegion can convert paths to contour paths by providing winding rules.
> 
> ```swift
> let original = try Shape(code: "M100 0c0-100-236.60 36.60-150 86.60S36.60-136.60-50-86.60 100 100 100 0z")
> let contour = ShapeRegion(original, winding: .nonZero)
> ```

I need to implement handwriting effect 

Did you know how to achieve this kind of effect?

I have font with character "A" -> then I convert this font to glyph bezier path. This give me result like picture in left side, it is "double contoured" I need "single contoured" path. I will show you animation in video below 

This is what I DON'T NEED

https://user-images.githubusercontent.com/29518174/202905983-a653ffb3-9d3c-41fe-b1ec-64c4298334c5.mp4

This is what I need


https://user-images.githubusercontent.com/29518174/202906178-8357e163-82b7-4476-8d03-afb0127b175d.mp4



Maybe inside your lib have some math function which can solve this kind of problem. convert "double contoured" path to "one countered path"
